spring:
  application:
    name: order-app

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50 # percentage
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        sliding-window-type: COUNT_BASED
  retry:
    instances:
      orderService:
        max-attempts: 3
        wait-duration: 5000
#  bulkhead: # semaphore
#    instances:
#      orderService:
#        max-wait-duration: 5000
#        max-concurrent-calls: 5
  thread-pool-bulkhead:
    instances:
      orderService:
        max-thread-pool-size: 1
        core-thread-pool-size: 1
        queue-capacity: 1
        writable-stack-trace-enabled: true
  ratelimiter:
    instances:
      orderService:
        limit-for-period: 2
        limit-refresh-period: 4s
        timeout-duration: 10s # Specifies the maximum time a thread should wait to acquire permission before giving up.
        register-health-indicator: true
        event-consumer-buffer-size: 100
  timelimiter:
    instances:
      orderService:
        timeout-duration: 2s
        cancel-running-future: true



management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
